export default[
  // 登录注册
  {
    path:'/user',
    component:'../layouts/UserLayout',
    routes:[
      { path:'/user', redirect:'/user/login' },
      { path:'/user/login', component:'./User/Login' },
      { path:'/user/register', component:'./User/Register' },
      { path:'/user/forgetpwd', component:'./User/Forgetpwd' },
      { path:'/user/test', component:'./User/Test' },
			{ path:'/user/personalinfo', component:'./User/PersonalInfo' },
    ]
  },
  {
    path:'/activity',
    component:'../layouts/UserLayout',
    routes:[
      { 
        path:'/activity',
        redirect:'/activity/release' 
      },
      { 
        path:'/activity/release',
        component:'./Activity/MyRelease' 
      },
      { 
        path:'/activity/participation',
        component:'./Activity/MyParticipation'
      },
      { 
        path:'/activity/myscore',
        component:'./Activity/MyScore'
      },
      { 
        path:'/activity/actdesign',
        component:'./Activity/ActDesign'
      },
      { 
        path:'/activity/actrecord',
        component:'./Activity/ActRecord'
      },
      { 
        path:'/activity/actmark',
        component:'./Activity/ActMark'
      },
      { 
        path:'/activity/actdetail',
        component:'./Activity/ActDetail'
      },
      { 
      	path:'/activity/activitydata',
      	component:'./Activity/ActivityData'
      },
      { 
      	path:'/activity/uploadworks',
      	component:'./Activity/UploadWorks'
      },
      { 
      	path:'/activity/actdetailmark',
      	component:'./Activity/Actdetailmark'
      }
    ]
  },
  {
    path:'/resource',
    component:'../layouts/UserLayout',
    routes:[
      { 
        path:'/resource',
        redirect:'/resource/course' 
      },
      { 
        path:'/resource/course',
        component:'./Resource/Course' 
      },
      { 
        path:'/resource/buys',
        component:'./Resource/Buys' 
      },
      { 
        path:'/resource/coursedetail',
        component:'./Resource/CourseDetail' 
      },
      { 
        path:'/resource/buydetail',
        component:'./Resource/BuyDetail' 
      },
      { 
        path:'/resource/createcourse',
        component:'./Resource/CreateCourse' 
      },
      { 
        path:'/resource/createsell',
        component:'./Resource/CreateSell' 
      },
      { 
        path:'/resource/sells',
        component:'./Resource/Sells' 
      },
      { 
        path:'/resource/test',
        component:'./Resource/Test' 
      },
      { 
        path:'/resource/seriescourse',
        component:'./Resource/SeriesCourse' 
      },
      { 
        path:'/resource/selldetail',
        component:'./Resource/SellDetail' 
      },
      { 
        path:'/resource/auction',
        component:'./Resource/Auction' 
      },
      { 
        path:'/resource/auctiondetail',
        component:'./Resource/AuctionDetail' 
      },
    ]
  },
  {
    path:'/',
    component:'../layouts/BasicLayout',
    routes:[
      {
        path:'/',
        component:'./Home',
        redirect:'/home'
      },
      {
        path:'/home',
        component:'./Home'
      },
      {
        path: '/home/detail',
        component:'./Home/HomeDetail'
      }
    ]
  },
]
